### ISSUE TITLE
ONE-CLASS SVM is not supported

### ISSUE THREAD

**Issue by acostapazo** [bioidiap/bob.learn.libsvm#4]
It would be interesting that the package had implemented this feature. It will allow us to train svm machines using only one class data.

I am going to fork the repo in order to submit a pull-request for OC-SVM support.

**Comment by anjos** [comment]
You're most welcome, please do so.

**Comment by tiagofrepereira2012** [comment]
Merged with the pull request #5.

Thanks @acostapazo
